export const ARCHIVE_ALL_CALL = "ARCHIVE_ALL_CALL";
export const UNARCHIVE_ALL_CALL = "UNARCHIVE_ALL_CALL";
export const ARCHIVE_A_CALL = "ARCHIVE_A_CALL";
export const UNARCHIVE_A_CALL = "UNARCHIVE_A_CALL";

export const ARCHIVED_PAGE = "ARCHIVED_PAGE"
export const UNARCHIVED_PAGE = "UNARCHIVED_PAGE"
